### ISSUE TITLE
[request] Make Movie.getFrameForLabel() public

### ISSUE THREAD

**Issue by matyasatfp** [threerings/flump#136]
I have a quite complex .fla file whose timeline looks like this: http://i.imgur.com/iijxnKI.png 
I convert this with the Flump exporter to Starling and load it.
I need 2 functions that are currently (to my best knowledge) very hard to accomplish with Flump:  
- Loop a part of the movie that is marked by a keyframe   
- play back a movie from a keyframe until 1 frame before the next keyframe.   

Both of these are cannot be done now, but if you make the  Movie:getFrameForLabel() function public it can be done easily. If this is OK, ill submit a PR.

**Comment by tconkling** [comment]
Sure - I just went ahead and made the change

**Comment by matyasatfp** [comment]
Thanks!


On Thu, Jan 15, 2015 at 19:40 PM, Tim Conkling <notifications@github.com>
wrote:

Sure - I just went ahead and made the change


—
Reply to this email directly or view it on GitHub
<https://github.com/threerings/flump/issues/136#issuecomment-70147859>.










-- 
Sent from MetroMail
