### ISSUE TITLE
How to access the frame number being played currently (MovieClip.currentFrame in AS3)?

### ISSUE THREAD

**Issue by ramachandran-prazas** [threerings/flump#138]
Hi,

Could you please let me know how I can access the current frame number being played. Its stored at MovieSprite._frame but since its private I cant access it. Is there any other way to do this?

Thanks for your help. 

BTW flump tool rocks :-)

**Comment by groves** [comment]
There's the `Movie.frame()` function that returns `_frame`. Does that get what you're after?

**Comment by ramachandran-prazas** [comment]
I don't seem to have the Movie class in my library. Is this part of flump? I am using flambe.

**Comment by tconkling** [comment]
Ah - you'll want to ask on the Flambe github. (Flambe is separate from
Flump - I don't have experience with it.) https://github.com/aduros/flambe
